models/__init__.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

models/user.py
from sqlalchemy import Column, Integer, String, ForeignKey

from models import db

user_role = db.Table('user_role',
                     Column('user_id', Integer, ForeignKey('user.id', name='user_role_fk')),
                     Column('role_id', Integer, ForeignKey('role.id', name='user_role_pk')),
                     )


class BaseModel(db.Model):
    __abstract__ = True
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(20), unique=True, nullable=False)


class Role(BaseModel):
    __tablename__ = 'role'


class Qx(BaseModel):
    __tablename__ = 'qx'


class User(db.Model):
    id = Column(Integer,
                primary_key=True,
                autoincrement=True)
    auth_key = Column(String(100), nullable=False)
    nick_name = Column(String(20))
    photo = Column(String(100))
    # Many-to-Many 多对多的关系，指定secondary设置关联的表，Table()
    roles = db.relationship(Role, secondary=user_role)

myapp/__init__.py
from flask import Flask

import settings

app = Flask(__name__)
app.config.from_object(settings.Dev)

myapp/views/index.py
from flask import render_template, request
from flask import Blueprint

from models.user import User
from utils import cache

blue = Blueprint('indexBlue', __name__)


@blue.route('/')
def index():
    # 获取用户登录的信息
    token = request.cookies.get('token')
    user_id = cache.get_user_id(token)
    user = User.query.get(int(user_id))

    return render_template('index.html', user=user)

myapp/views/user.py
import os
from datetime import datetime, timedelta
import uuid

from flask import render_template, request, redirect, jsonify
from flask import Blueprint
from werkzeug.datastructures import FileStorage

import settings
from models import db
from models.user import User
from utils import crypt, cache

blue = Blueprint('userBlue', __name__)


# 修改用户信息
@blue.route('/modify', methods=['GET', 'POST'])
def modify():
    token = request.cookies.get('token')
    user_id = cache.get_user_id(token)
    # 任务2： 优化登录用户的相关信息存在redis中(缓存)
    user = User.query.get(int(user_id))
    if request.method == 'POST':
        nick_name = request.form.get('nick_name')
        password = request.form.get('password')
        # 修改用户信息
        user.nick_name = nick_name
        user.auth_key = password
        # db.session.commit()
    return render_template('user/info.html',
                           user=user)

# ajax头像上传
@blue.route('/upload', methods=['POST'])
def upload_photo():
    upload_file: FileStorage = request.files.get('photo')

    filename = uuid.uuid4().hex + os.path.splitext(upload_file.filename)[-1]
    filepath = os.path.join(settings.USER_DIR, filename)

    upload_file.save(filepath)

    user = User.query.get(cache.get_user_id(request.cookies.get('token')))
    # 任务1：删除之前的用户头像
    if user.photo:
        pre_img = os.path.join(settings.USER_DIR, user.photo.split('/')[1])
        os.remove(pre_img)

    # 修改新头像的路径
    user.photo = 'user/' + filename
    # db.session.commit()

    # ? 图片如何压缩- PIL(pip install pillow)

    return jsonify({
        'msg': '上传成功',
        'path': 'user/' + filename,
    })


# 用户登录功能
@blue.route('/login', methods=['GET', 'POST'])
def login():
    message = ''
    if request.method == 'POST':
        nick_name = request.form.get('nick_name')
        passwd = request.form.get('passwd')
        # 去数据库查询是否有此用户
        login_user = User.query.filter(User.nick_name == nick_name,
                                      User.auth_key == passwd).first()
        if login_user:
            # 登录成功
            # 生成token
            token = uuid.uuid4().hex
            resp = redirect('/')
            resp.set_cookie('token', token, expires=(datetime.now() + timedelta(days=3)))
            # 将token添加到redis, token-user_id
            cache.save_token(token, login_user.id)
            return resp
        else:
            message = '查无此用户'

    return render_template('user/login.html', msg=message)

utils/__init__.py
from redis import Redis

rd = Redis(host='192.168.43.112',
           db=9,
           decode_responses=True)

myapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Title</title>
    <style>
        .circle-img {
            border: none;
            width: 100px;
            height: 100px;
            border-radius: 50%;
            box-shadow: 5px 5px 5px lightgray;
        }
    </style>
</head>
<body>
 <h1>主页</h1>
 <p>
     <img class="circle-img"
          id="photoImg"
          title="点击图片更改"
          onclick="selectImg()"
          src="/static/{% if user.photo %}{{ user.photo }}{% else %}images/default_img.png{% endif %}" />
 </p>
 <input type="file"
        id="selectFile"
        style="display: none"
        onchange="upload(this.files[0])">

 <h3><a href="{{ url_for("userBlue.modify") }}">修改个人信息</a></h3>
<script>
    function $(domID) {
        return document.getElementById(domID)
    }
    function selectImg() {
        if(confirm('是否确定更改头像')){
            $('selectFile').click()
        }
    }

    function upload(file) {
        {# alert(file.name); #}
        {# console.log(file) #}

        if(file.type.startsWith('image/')){
            if(file.size <= 1024*1024*8){
                // 任务2： 使用fetch()函数实现文件上传
                let url ="{{ url_for('userBlue.upload_photo') }}"
                let request = new XMLHttpRequest();
                request.open('post', url, true);
                request.onload = function (ev) {
                    respText = request.responseText;
                    respJson = JSON.parse(respText)
                    console.log(respText, respJson)
                    $('photoImg').src='/static/'+respJson.path;

                };
                let formdata = new FormData();
                formdata.append('photo', file)

                // 发送请求
                request.send(formdata)

            }else{
               alert('上传的图片大小在2M以内')
            }
        }else{
           alert('只限图片上传')
        }
    }
</script>
</body>
</html>

myapp/templates/user/info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{{ user.nick_name }}的个人中心</title>
</head>
<body>
<!-- 如果form表单请求的路径是当前url路径,可以省略 action='user/modify' -->
<form method="post" action="/user/modify">
    用户名:<input id="nick_name" type="text" name="nick_name" value="{{ user.nick_name }}"><br/>
    密码:<input password="password" type="password" name="password" value="{{ user.auth_key }}"><br/>
    <button>保存修改</button>
</form>
<script>
    function $(id) {
         return document.getElementById(id);
     }

     // 设置表单提交函数
     document.forms[0].onsubmit = function(ev){
          if(! /\w{6,}/.test(this.passwd.value)){
             $('val_info').innerHTML = '口令是包含数字和字母的至少6位的字符串';
             return false
         }
     }
</script>
</body>
</html>

myapp/templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Login</title>
</head>
<body>
  <h1> 用户登录页面</h1>
  <form name="login_form" action="/user/login" method="post">
      <input name="nick_name" placeholder="用户名"><br>
      <input type="password" name="passwd" placeholder="口令"><br>
      <button>登录</button> <a href="#">没有账号则先去注册</a>
  </form>
  <div id="val_info" style="color:red">
      {{ msg }}
  </div>
 <script>
     function $(id) {
         return document.getElementById(id);
     }

     // 设置表单提交函数
     document.forms[0].onsubmit = function(ev){
          if(! /\w{6,}/.test(this.passwd.value)){
             console.log(this.passwd.value);
             $('val_info').innerHTML = '口令是包含数字和字母的至少6位的字符串';
             return false
         }
          $('val_info').innerHTML = ''
     }
 </script>
</body>
</html>